/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOERFDIJETFUNCTION
#define ROOERFDIJETFUNCTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooErfDijetFunction : public RooAbsPdf {
public:
  RooErfDijetFunction() {} ; 
  RooErfDijetFunction( const char *name, const char *title,
		   RooAbsReal& _x,
		   RooAbsReal& _k1,
		   RooAbsReal& _k2,
		   RooAbsReal& _k3,
		   RooAbsReal& _k4 );
  RooErfDijetFunction(const RooErfDijetFunction& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooErfDijetFunction(*this,newname); }
  inline virtual ~RooErfDijetFunction() { }

protected:

  RooRealProxy x ;
  RooRealProxy k1 ;
  RooRealProxy k2 ;
  RooRealProxy k3 ;
  RooRealProxy k4 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooErfDijetFunction,1) // Your description goes here...
};
 
#endif
