/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODOUBLEERFDIJETFUNCTION
#define ROODOUBLEERFDIJETFUNCTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooDoubleErfDijetFunction : public RooAbsPdf {
public:
  RooDoubleErfDijetFunction() {} ; 
  RooDoubleErfDijetFunction( const char *name, const char *title,
			     RooAbsReal& _x,
			     RooAbsReal& _k1,
			     RooAbsReal& _k2,
			     RooAbsReal& _m1,
			     RooAbsReal& _w1,
			     RooAbsReal& _m2,
			     RooAbsReal& _w2 );
  RooDoubleErfDijetFunction(const RooDoubleErfDijetFunction& other, 
			    const char* name=0) ;
  virtual TObject* clone(const char* newname) const 
  { return new RooDoubleErfDijetFunction(*this,newname); }
  inline virtual ~RooDoubleErfDijetFunction() { }

protected:

  RooRealProxy x ;
  RooRealProxy k1 ;
  RooRealProxy k2 ;
  RooRealProxy m1 ;
  RooRealProxy w1 ;
  RooRealProxy m2 ;
  RooRealProxy w2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooDoubleErfDijetFunction,1) // Your description goes here...
};
 
#endif
