/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "BkgRooErfDijetFunction.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooErfDijetFunction) 

 RooErfDijetFunction::RooErfDijetFunction( const char *name, 
				   const char *title, 
				   RooAbsReal& _x,
				   RooAbsReal& _k1,
				   RooAbsReal& _k2,
				   RooAbsReal& _k3,
				   RooAbsReal& _k4 ) : 
RooAbsPdf(name,title),
  x("x","x",this,_x), 
  k1("k1","k1",this,_k1), 
  k2("k2","k2",this,_k2),
  k3("k3","k3",this,_k3),
  k4("k4","k4",this,_k4)
 { 
 } 


 RooErfDijetFunction::RooErfDijetFunction(const RooErfDijetFunction& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   k1("k1",this,other.k1),
   k2("k2",this,other.k2),
   k3("k3",this,other.k3),
   k4("k4",this,other.k4)
 { 
 } 



 Double_t RooErfDijetFunction::evaluate() const 
 { 

   return pow(x,k1*(1.-log(x)))*pow(x,k2*log(x))*(1.-1./(1+exp((x-k3)/k4)));

   // return pow(x, k1) * pow(x, k2 * log(x));
 } 



